import { User, CurrentUser, Relationship, Chat, Message, Moment, Location } from '@/types';

// Mock current user
export const mockCurrentUser: CurrentUser = {
  id: 'user-1',
  username: 'you',
  displayName: 'You',
  avatar: 'https://i.pravatar.cc/150?img=1',
  phoneNumber: '+84901234567',
  status: 'online',
  accentColor: 'pink',
  theme: 'light',
  fontSize: 16,
  locationSharing: true,
  ghostMode: false,
};

// Mock users
export const mockUsers: User[] = [
  {
    id: 'user-2',
    username: 'partner',
    displayName: 'My Love ❤️',
    avatar: 'https://i.pravatar.cc/150?img=5',
    phoneNumber: '+84907654321',
    status: 'online',
    bio: 'Together since 2024',
  },
  {
    id: 'user-3',
    username: 'bestfriend',
    displayName: 'Best Friend',
    avatar: 'https://i.pravatar.cc/150?img=8',
    phoneNumber: '+84909876543',
    status: 'online',
    bio: 'Always there for you',
  },
  {
    id: 'user-4',
    username: 'john',
    displayName: 'John Doe',
    avatar: 'https://i.pravatar.cc/150?img=12',
    phoneNumber: '+84908765432',
    status: 'offline',
    lastSeen: new Date(Date.now() - 3600000),
    bio: 'Just living life',
  },
  {
    id: 'user-5',
    username: 'alice',
    displayName: 'Alice',
    avatar: 'https://i.pravatar.cc/150?img=20',
    phoneNumber: '+84903456789',
    status: 'offline',
    lastSeen: new Date(Date.now() - 7200000),
    bio: 'Adventure seeker',
  },
];

// Mock relationships
export const mockRelationships: Relationship[] = [
  {
    userId: 'user-2',
    status: 'couple',
    user: mockUsers[0],
    isPinned: true,
    isMuted: false,
    isBlocked: false,
    chatTheme: 'pink',
  },
  {
    userId: 'user-3',
    status: 'friend',
    user: mockUsers[1],
    isPinned: false,
    isMuted: false,
    isBlocked: false,
  },
  {
    userId: 'user-4',
    status: 'friend',
    user: mockUsers[2],
    isPinned: false,
    isMuted: false,
    isBlocked: false,
  },
  {
    userId: 'user-5',
    status: 'friend',
    user: mockUsers[3],
    isPinned: false,
    isMuted: false,
    isBlocked: false,
  },
];

// Mock chats
export const mockChats: Chat[] = [
  {
    id: 'chat-1',
    type: '1-1',
    participants: ['user-1', 'user-2'],
    lastMessage: {
      id: 'msg-1',
      chatId: 'chat-1',
      senderId: 'user-2',
      type: 'text',
      content: 'Miss you! 💕',
      timestamp: new Date(Date.now() - 300000),
      status: 'seen',
    },
    unreadCount: 0,
    isPinned: true,
    isMuted: false,
    relationshipStatus: 'couple',
    theme: 'pink',
  },
  {
    id: 'chat-2',
    type: '1-1',
    participants: ['user-1', 'user-3'],
    lastMessage: {
      id: 'msg-2',
      chatId: 'chat-2',
      senderId: 'user-3',
      type: 'text',
      content: 'Want to hang out later?',
      timestamp: new Date(Date.now() - 1800000),
      status: 'delivered',
    },
    unreadCount: 1,
    isPinned: false,
    isMuted: false,
    relationshipStatus: 'friend',
  },
  {
    id: 'chat-3',
    type: '1-1',
    participants: ['user-1', 'user-4'],
    lastMessage: {
      id: 'msg-3',
      chatId: 'chat-3',
      senderId: 'user-1',
      type: 'text',
      content: 'Cool, see you!',
      timestamp: new Date(Date.now() - 3600000),
      status: 'seen',
    },
    unreadCount: 0,
    isPinned: false,
    isMuted: false,
    relationshipStatus: 'friend',
  },
  {
    id: 'chat-4',
    type: '1-1',
    participants: ['user-1', 'user-5'],
    lastMessage: {
      id: 'msg-4',
      chatId: 'chat-4',
      senderId: 'user-5',
      type: 'text',
      content: 'Check out this photo!',
      timestamp: new Date(Date.now() - 7200000),
      status: 'delivered',
    },
    unreadCount: 2,
    isPinned: false,
    isMuted: false,
    relationshipStatus: 'friend',
  },
];

// Mock messages for chat-1
export const mockMessages: Message[] = [
  {
    id: 'msg-10',
    chatId: 'chat-1',
    senderId: 'user-1',
    type: 'text',
    content: 'Good morning! ☀️',
    timestamp: new Date(Date.now() - 7200000),
    status: 'seen',
  },
  {
    id: 'msg-11',
    chatId: 'chat-1',
    senderId: 'user-2',
    type: 'text',
    content: 'Morning! Did you sleep well?',
    timestamp: new Date(Date.now() - 7000000),
    status: 'seen',
  },
  {
    id: 'msg-12',
    chatId: 'chat-1',
    senderId: 'user-1',
    type: 'text',
    content: 'Yes! Dreamed about you 😊',
    timestamp: new Date(Date.now() - 6800000),
    status: 'seen',
  },
  {
    id: 'msg-13',
    chatId: 'chat-1',
    senderId: 'user-2',
    type: 'text',
    content: 'Aww that is so sweet! 💕',
    timestamp: new Date(Date.now() - 6600000),
    status: 'seen',
  },
  {
    id: 'msg-14',
    chatId: 'chat-1',
    senderId: 'user-2',
    type: 'text',
    content: 'What are you doing today?',
    timestamp: new Date(Date.now() - 6400000),
    status: 'seen',
  },
  {
    id: 'msg-15',
    chatId: 'chat-1',
    senderId: 'user-1',
    type: 'text',
    content: 'Working until 6pm, then free!',
    timestamp: new Date(Date.now() - 6200000),
    status: 'seen',
  },
  {
    id: 'msg-16',
    chatId: 'chat-1',
    senderId: 'user-2',
    type: 'text',
    content: 'Want to grab dinner together? 🍜',
    timestamp: new Date(Date.now() - 6000000),
    status: 'seen',
  },
  {
    id: 'msg-17',
    chatId: 'chat-1',
    senderId: 'user-1',
    type: 'text',
    content: 'Yes! Where do you want to go?',
    timestamp: new Date(Date.now() - 5800000),
    status: 'seen',
  },
  {
    id: 'msg-18',
    chatId: 'chat-1',
    senderId: 'user-2',
    type: 'text',
    content: 'That new ramen place?',
    timestamp: new Date(Date.now() - 5600000),
    status: 'seen',
  },
  {
    id: 'msg-19',
    chatId: 'chat-1',
    senderId: 'user-1',
    type: 'text',
    content: 'Perfect! See you at 6:30pm 💕',
    timestamp: new Date(Date.now() - 5400000),
    status: 'seen',
  },
  {
    id: 'msg-1',
    chatId: 'chat-1',
    senderId: 'user-2',
    type: 'text',
    content: 'Miss you! 💕',
    timestamp: new Date(Date.now() - 300000),
    status: 'seen',
  },
];

// Mock moments
export const mockMoments: Moment[] = [
  {
    id: 'moment-1',
    userId: 'user-2',
    user: mockUsers[0],
    imageUrl: 'https://picsum.photos/400/600?random=1',
    caption: 'Beautiful sunset today 🌅',
    timestamp: new Date(Date.now() - 3600000),
    visibility: 'friends',
    reactions: [
      { userId: 'user-1', emoji: '❤️', timestamp: new Date(Date.now() - 3000000) },
      { userId: 'user-3', emoji: '😍', timestamp: new Date(Date.now() - 2800000) },
    ],
    comments: [
      {
        id: 'comment-1',
        userId: 'user-1',
        user: mockCurrentUser,
        content: 'So pretty! 💕',
        timestamp: new Date(Date.now() - 3200000),
      },
    ],
  },
  {
    id: 'moment-2',
    userId: 'user-3',
    user: mockUsers[1],
    imageUrl: 'https://picsum.photos/400/600?random=2',
    caption: 'Coffee time ☕',
    timestamp: new Date(Date.now() - 7200000),
    visibility: 'friends',
    reactions: [
      { userId: 'user-1', emoji: '👍', timestamp: new Date(Date.now() - 6800000) },
    ],
    comments: [],
  },
  {
    id: 'moment-3',
    userId: 'user-4',
    user: mockUsers[2],
    imageUrl: 'https://picsum.photos/400/600?random=3',
    caption: 'New place discovered! 🏞️',
    timestamp: new Date(Date.now() - 10800000),
    visibility: 'friends',
    reactions: [
      { userId: 'user-1', emoji: '🔥', timestamp: new Date(Date.now() - 10000000) },
      { userId: 'user-2', emoji: '😮', timestamp: new Date(Date.now() - 9800000) },
    ],
    comments: [
      {
        id: 'comment-2',
        userId: 'user-1',
        user: mockCurrentUser,
        content: 'Where is this?',
        timestamp: new Date(Date.now() - 10200000),
      },
      {
        id: 'comment-3',
        userId: 'user-4',
        user: mockUsers[2],
        content: 'Near the mountains!',
        timestamp: new Date(Date.now() - 10000000),
      },
    ],
  },
  {
    id: 'moment-4',
    userId: 'user-5',
    user: mockUsers[3],
    imageUrl: 'https://picsum.photos/400/600?random=4',
    caption: 'Workout done! 💪',
    timestamp: new Date(Date.now() - 14400000),
    visibility: 'friends',
    reactions: [
      { userId: 'user-1', emoji: '💪', timestamp: new Date(Date.now() - 14000000) },
    ],
    comments: [],
  },
];

// Mock locations
export const mockLocations: Location[] = [
  {
    userId: 'user-2',
    latitude: 21.0285,
    longitude: 105.8542,
    timestamp: new Date(),
    accuracy: 10,
    address: 'Hoàn Kiếm, Hà Nội',
  },
  {
    userId: 'user-3',
    latitude: 21.0245,
    longitude: 105.8412,
    timestamp: new Date(),
    accuracy: 15,
    address: 'Ba Đình, Hà Nội',
  },
  {
    userId: 'user-4',
    latitude: 21.0368,
    longitude: 105.8345,
    timestamp: new Date(Date.now() - 3600000),
    accuracy: 20,
    address: 'Đống Đa, Hà Nội',
  },
  {
    userId: 'user-5',
    latitude: 21.0122,
    longitude: 105.8253,
    timestamp: new Date(Date.now() - 7200000),
    accuracy: 25,
    address: 'Thanh Xuân, Hà Nội',
  },
];
